-- LISTANDO TODOS REGISTRO DA TABELA
SELECT * FROM PRODUTOS

--LISTANDO TODOS CLIENTES E SEUS RESPECTIVOS PEDIDOS
SELECT C.NOME, P.ID_PEDIDO, P.DATA_PEDIDO
    FROM CLIENTES C JOIN PEDIDOS P
    ON C.ID_CLIENTE = P.ID_PEDIDO
    ORDER BY C.NOME
 
-- LISTANDO TODOS OS PRODUTOS VENDIDOS DE UM DETERMINADO PEDIDO    
SELECT P.*
FROM PRODUTOS P
INNER JOIN ITEM_PEDIDOS IP ON P.ID_PRODUTO = IP.ID_PRODUTO
WHERE IP.ID_PEDIDO = 2

--LISTANDO TOTAL DE VENDAS POR PRODUTOS
SELECT P.NOME AS NOME_PRODUTO, SUM(IP.QUANTIDADE) AS TOTAL_VENDAS
FROM PRODUTOS P
INNER JOIN ITEM_PEDIDOS IP ON P.ID_PRODUTO = IP.ID_PRODUTO
GROUP BY P.NOME;


    COMMIT 
    

