-- TABELA DE PRODUTOS --

CREATE TABLE PRODUTOS (
    ID_PRODUTO NUMBER PRIMARY KEY,
    NOME VARCHAR2 (50),
    DESCRICAO VARCHAR2(100),
    PRECO_UNIT NUMBER (10, 2)
);

--TABELA DE CLIENTES--

CREATE TABLE CLIENTES (
    ID_CLIENTE NUMBER PRIMARY KEY,
    NOME VARCHAR2 (50),
    EMAIL VARCHAR2 (100),
    TELEFONE NUMBER (20)
);

--TABELA DE PEDIDOS--

CREATE TABLE PEDIDOS (
    ID_PEDIDO NUMBER (10) PRIMARY KEY,
    ID_CLIENTE NUMBER (10) REFERENCES CLIENTES(ID_CLIENTE),
    DATA_PEDIDO DATE
);

-- TABELA DE ITEM PEDIDO--

CREATE TABLE ITEM_PEDIDOS (
    ID_ITEM NUMBER (10) PRIMARY KEY,
    ID_PEDIDO NUMBER (10) REFERENCES PEDIDOS (ID_PEDIDO),
    ID_PRODUTO NUMBER (10) REFERENCES PRODUTOS (ID_PRODUTO),
    QUANTIDADE NUMBER (10)
);

-- INSERINDO PRODUTOS --

INSERT INTO PRODUTOS VALUES (1,'IPHONE 11', 'SMARTHPHONE COM CAMERA DE ALTA RESOLU��O', 4000.00);
INSERT INTO PRODUTOS VALUES (2,'NOTEBOOCK GAMMING', 'NOTEBOOCK COM SUPER DESEMPENHO PARA JOGOS', 15000.00);
INSERT INTO PRODUTOS VALUES (3,'SMARTWATCH', 'REL�GIO INTELIGENTE COM MONITOR CARD�ACO', 1000.00);

-- INSERIRINDO CLIENTES -- 

INSERT INTO CLIENTES VALUES (1,'MARCONDES PEDRO', 'MARCONDES@GMAIL.COM', 8199744-9467);
INSERT INTO CLIENTES VALUES (2,'LIGIA SALES', 'LIGIA_COM@GMAIL.COM', 8199744-0721);
INSERT INTO CLIENTES VALUES (3,'ROSILDA MARIA', 'ROSILDA@HOTMAIL.COM', 8199877-1310);

-- INSERINDO PEDIDOS -- 

INSERT INTO PEDIDOS VALUES (1, 1, TO_DATE('2022/12/20', 'YYYY/MM/DD'));
INSERT INTO PEDIDOS VALUES (2, 2, TO_DATE('2022/11/22', 'YYYY/MM/DD'));
INSERT INTO PEDIDOS VALUES (3, 3, TO_DATE('2022/10/23', 'YYYY/MM/DD'));

-- INSERINDO ITEM_PEDIDOS --

INSERT INTO ITEM_PEDIDOS VALUES (1, 1, 1, 4);
INSERT INTO ITEM_PEDIDOS VALUES (2, 1, 2, 2);
INSERT INTO ITEM_PEDIDOS VALUES (3, 2, 3, 3);
INSERT INTO ITEM_PEDIDOS VALUES (4, 3, 1, 1);
INSERT INTO ITEM_PEDIDOS VALUES (5, 3, 3, 2);


-- VERIFICANDO DE QUANTIDADE DE PRODUTOS -- 

SELECT nome, COUNT(*) AS "TOTAL DE PRODUTOS"
FROM Produtos
GROUP BY nome;




